export const ACTIONS = {
    EXECUTE_AUTOMATION: "EXECUTE_AUTOMATION",
    END_AUTOMATION: "END_AUTOMATION",
    PROCESS_NEXT_LECTURE: "PROCESS_NEXT_LECTURE",
    GET_STATE: "GET_STATE",
    KEEP_ALIVE: "KEEP_ALIVE",
    OPEN_LECTURE_TAB: "OPEN_LECTURE_TAB",
    CLOSE_CURRENT_TAB: "CLOSE_CURRENT_TAB",
};

export const STORAGE_KEYS = {
    CURRENT_LECTURE_INDEX: "currentLectureIndex",
};
